apiVersion: v1
kind: ConfigMap
metadata:
  name: financial-config
  namespace: financial-platform
data:
  DB_URL: jdbc:postgresql://postgres:5432/financial_enrollment
  DB_USERNAME: financial_user
  REDIS_HOST: redis
  REDIS_PORT: "6379"
