server:
  port: ${SERVER_PORT:8085}
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/financial_enrollment}
    username: ${DB_USERNAME:financial_user}
    password: ${DB_PASSWORD:financial_pass}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
management:
  endpoints:
    web:
      exposure:
        include: health,info
